steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions',
      'deploy',
      'buildNotify',
      'send',
      '--runtime',
      'nodejs8',
      '--trigger-topic',
      'cloud-build'
    ]
    dir: 'functions'