steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/bekraf-developer-conference/staging-rewards-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/bekraf-developer-conference/staging-rewards-api', 'npm', 'run', 'test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bekraf-developer-conference/staging-rewards-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'staging-rewards-api', '--image=gcr.io/bekraf-developer-conference/staging-rewards-api', '--region', 'asia-northeast1', '--platform=managed', '--allow-unauthenticated']